### ISSUE TITLE
please submit the missing resource 

### ISSUE THREAD

**Issue by lolstudio** [Yasic/DiyCodeForAndroid#1]
Hi. i watched and build your repo is to learn MVP ,but has some trouble, it's missing resoure, please submit them, thx, Detail:

Error:(64, 34) No resource found that matches the given name (at 'src' with value '@drawable/ic_star_border_pink_400_24dp').
Error:(70, 34) No resource found that matches the given name (at 'src' with value '@drawable/ic_reply_blue_a400_24dp').

**Comment by Yasic** [comment]
Hi! I am sorry for this little mistake and I have upload these files just now. Please enjoy it!
